version: "3.0"

networks:
  joinc-nw:

services:
  counter-app:
    image: joinc/counter:latest
    ports:
      - "8000:8000"
    depends_on:
      - counter-db 
    networks:
      - joinc-nw
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: "counter"
      MYSQL_PORT: "3306"
      MYSQL_HOST: "counter-db"

  counter-db:
    image: mysql:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - joinc-nw